### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by amiguet** [home-assistant-libs/pytradfri#257]
Basic test in standalone mode
```
 python3 -i -m pytradfri IP
```
results in error
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File ".../venv/lib/python3.8/site-packages/pytradfri/__main__.py", line 76, in <module>
    moods = api(gateway.get_moods())
  File ".../venv/lib/python3.8/site-packages/pytradfri/api/libcoap_api.py", line 96, in request
    return self._execute(api_commands, timeout=timeout)
  File ".../venv/lib/python3.8/site-packages/pytradfri/api/libcoap_api.py", line 90, in _execute
    api_command.result = _process_output(return_value, parse_json)
  File ".../venv/lib/python3.8/site-packages/pytradfri/command.py", line 68, in result
    self._result = self._process_result(value)
  File ".../venv/lib/python3.8/site-packages/pytradfri/gateway.py", line 115, in process_result
    return [self.get_mood(mood, mood_parent=mood_parent) for mood in
TypeError: 'NoneType' object is not iterable

>>>
```
pytradfri 6.4.0 on linux.

README examples like `api(lights[1].light_control.set_dimmer(50))` still work, though.

Any idea what's happening?

**Comment by ggravlingen** [comment]
Do you have any moods setup when you look in the IKEA app?

**Comment by amiguet** [comment]
Yes I saved a couple of moods.

**Comment by ggravlingen** [comment]
The example doesn’t have moods, that’s probably why it works. What happens if you comment those moods line out in the __main__ file in your lib folder?

**Comment by amiguet** [comment]
Yes, if I comment out the moods lines it works. Thanks! I yet have to fully understand the authentication mechanism, but at least now I can run something without errors!
Is the problem with moods a bug or some king of a feature?
