### ISSUE TITLE
Error installing pytradfri[async] 7.0.6

### ISSUE THREAD

**Issue by Squashyware** [home-assistant-libs/pytradfri#304]
Using in HomeAssitant Core in a venv - python 3,8

pytradfri 7.0.6 installed

Backend used (aiocoap, libcoap) - not sure!

Tried pip3 install --upgrade pytradfri[async]

```

(homeassistant) homeassistant@hass:/srv/homeassistant$ pip3 install --upgrade pytradfri[async]
Collecting pytradfri[async]
  Using cached pytradfri-7.0.6-py3-none-any.whl (30 kB)
Requirement already satisfied, skipping upgrade: aiocoap==0.4b3; extra == "async" in ./lib/python3.8/site-packages (from pytradfri[async]) (0.4b3)
Collecting DTLSSocket==0.1.12; extra == "async"
  Using cached DTLSSocket-0.1.12.tar.gz (150 kB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /srv/homeassistant/bin/python3 /srv/homeassistant/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-jjbtkr9i/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- Cython setuptools wheel
       cwd: None
  Complete output (44 lines):
  Traceback (most recent call last):
    File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/srv/homeassistant/lib/python3.8/site-packages/pip/__main__.py", line 19, in <module>
      sys.exit(_main())
    File "/srv/homeassistant/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 73, in main
      command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
    File "/srv/homeassistant/lib/python3.8/site-packages/pip/_internal/commands/__init__.py", line 96, in create_command
      module = importlib.import_module(module_path)
    File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 783, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "/srv/homeassistant/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 24, in <module>
      from pip._internal.cli.req_command import RequirementCommand
    File "/srv/homeassistant/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 21, in <module>
      from pip._internal.req.constructors import (
    File "/srv/homeassistant/lib/python3.8/site-packages/pip/_internal/req/__init__.py", line 11, in <module>
      from .req_file import parse_requirements
    File "/srv/homeassistant/lib/python3.8/site-packages/pip/_internal/req/req_file.py", line 25, in <module>
      from pip._internal.req.constructors import (
    File "/srv/homeassistant/lib/python3.8/site-packages/pip/_internal/req/constructors.py", line 28, in <module>
      from pip._internal.req.req_install import InstallRequirement
    File "/srv/homeassistant/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 17, in <module>
      from pip._vendor.pep517.wrappers import Pep517HookCaller
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
    File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
    File "<frozen zipimport>", line 259, in load_module
    File "/srv/homeassistant/share/python-wheels/pep517-0.8.2-py2.py3-none-any.whl/pep517/wrappers.py", line 14, in <module>
    File "/usr/lib/python3.8/importlib/resources.py", line 11, in <module>
      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401
    File "/srv/homeassistant/lib/python3.8/site-packages/typing.py", line 1357, in <module>
      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
    File "/srv/homeassistant/lib/python3.8/site-packages/typing.py", line 1005, in __new__
      self._abc_registry = extra._abc_registry
  AttributeError: type object 'Callable' has no attribute '_abc_registry'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /srv/homeassistant/bin/python3 /srv/homeassistant/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-jjbtkr9i/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- Cython setuptools wheel Check the logs for full command output.


```

**Comment by MartinHjelmare** [comment]
Uninstall the `typing` package from your environment. It's interfering and not needed in Python 3.8 as it's already in standard library.

**Comment by Squashyware** [comment]
You are a star! Thank You.
Even knowing the answer, its not clear to me from the output what the issue is!
