### ISSUE TITLE
Running python3 -i -m pytradfri GatewayIP gives FileNotFoundError

### ISSUE THREAD

**Issue by Fusion1013** [home-assistant-libs/pytradfri#306]
### Where are you using pytradfri (eg stand-alone, Home Assistant etc)
stand-alone

### Version of pytradfri
Latest from pip3

### Backend used (aiocoap, libcoap)
libcoap

### Expected behaviour
Running `python3 -i -m pytradfri GatewayIP` should work

### Actual behaviour
Running `python3 -i -m pytradfri GatewayIP` gives the following:

`Traceback (most recent call last):
  File "G:\Dokument\Python\Tradfri\pytradfri-master\pytradfri\__main__.py", line 50, in <module>
    identity = conf[args.host].get("identity")
KeyError: 'GatewayIP'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "G:\Dokument\Python\Tradfri\pytradfri-master\pytradfri\__main__.py", line 58, in <module>
    psk = api_factory.generate_psk(args.key)
  File "G:\Dokument\Python\Tradfri\pytradfri-master\pytradfri\api\libcoap_api.py", line 167, in generate_psk
    self._psk = self.request(Gateway().generate_psk(existing_psk_id))
  File "G:\Dokument\Python\Tradfri\pytradfri-master\pytradfri\api\libcoap_api.py", line 94, in request
    return self._execute(api_commands, timeout=timeout)
  File "G:\Dokument\Python\Tradfri\pytradfri-master\pytradfri\api\libcoap_api.py", line 82, in _execute
    return_value = subprocess.check_output(command, **kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] File not found`

**Comment by ggravlingen** [comment]
Looks like you're running Windows? I haven't tried it myself so I don't know how to get it running. Maybe this issue could give you some hints?
https://github.com/home-assistant-libs/pytradfri/issues/97

**Comment by therealscienta** [comment]
I also had the same issue, running on Windows 10. Instead tried it in a LXC Debian 10.7 and got the following:

`(tradfri) root@API:/var/tradfri# python -i -m pytradfri 192.168.1.12

DEBUG:pytradfri.util:JSON file not found: tradfri_standalone_psk.conf
Please provide the 'Security Code' on the back of your Tradfri gateway: XXXXXXXXXXXXXXXX
DEBUG:pytradfri.util:JSON file not found: tradfri_standalone_psk.conf
DEBUG:pytradfri.api.libcoap_api:Executing 192.168.1.12 post ['15011', '9063']: {'9090': 'ba46e3719ae042a79d4c86da5e401096'}
Traceback (most recent call last):
  File "/var/tradfri/tradfri/lib/python3.8/site-packages/pytradfri/__main__.py", line 50, in <module>
    identity = conf[args.host].get("identity")
KeyError: '192.168.1.12'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/var/tradfri/tradfri/lib/python3.8/site-packages/pytradfri/__main__.py", line 58, in <module>
    psk = api_factory.generate_psk(args.key)
  File "/var/tradfri/tradfri/lib/python3.8/site-packages/pytradfri/api/libcoap_api.py", line 167, in generate_psk
    self._psk = self.request(Gateway().generate_psk(existing_psk_id))
  File "/var/tradfri/tradfri/lib/python3.8/site-packages/pytradfri/api/libcoap_api.py", line 94, in request
    return self._execute(api_commands, timeout=timeout)
  File "/var/tradfri/tradfri/lib/python3.8/site-packages/pytradfri/api/libcoap_api.py", line 82, in _execute
    return_value = subprocess.check_output(command, **kwargs)
  File "/usr/local/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'coap-client'`

Installed libs:

Package    Version
---------- -------
aiocoap    0.4b3
pip        20.3.3
pytradfri  7.0.6
setuptools 51.3.3
wheel      0.36.2


What is ´identity´?
