### ISSUE TITLE
installs but fails on rpi4

### ISSUE THREAD

**Issue by dagrende** [home-assistant-libs/pytradfri#408]
### Where are you using pytradfri (eg stand-alone, Home Assistant etc)
standalone
### Version of pytradfri
clone of ef2614b
### Backend used (aiocoap, libcoap)
included in your docker file
### What type of environment are you in, eg Dockerized, Raspberry PI, VirtualBox, WiFi network (give as much details as possible)
Raspberry Pi 4 2GB
Linux rpi4 5.10.63-v7l+ #1457 SMP Tue Sep 28 11:26:14 BST 2021 armv7l
Docker version 20.10.12, build e91ed57
### Expected behaviour
./script/dev_docker
...
root@rpi4:/usr/src/app# python3 -i -m pytradfri 192.168.0.9
DEBUG:pytradfri.util:JSON file not found: tradfri_standalone_psk.conf
Please provide the 'Security Code' on the back of your Tradfri gateway: xxxxx
### Actual behaviour
./script/dev_docker
...
root@rpi4:/usr/src/app# python3 -i -m pytradfri 192.168.0.9
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/src/app/pytradfri/__init__.py", line 11, in <module>
    from .gateway import Gateway
  File "/usr/src/app/pytradfri/gateway.py", line 4, in <module>
    from .command import Command
  File "/usr/src/app/pytradfri/command.py", line 2
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
>>> 

I have attached the whole log for installing and running pytradfri.

I ran the same installation for the same gateway, on my Ubuntu laptop with success

[pytradfri-docker-rpi4-error2.txt](https://github.com/home-assistant-libs/pytradfri/files/7891879/pytradfri-docker-rpi4-error2.txt)
.

**Comment by ggravlingen** [comment]
We probably haven't kept the Docker image up to speed with the Python version minimum requirements of this library. 
If you replace the first line [here](https://github.com/home-assistant-libs/pytradfri/blob/2221ebe18389221cd3ddcbc83e9a5caafc207bc2/DockerfileRPI#L1) with this:
`FROM python:3.9` it'll probably work

**Comment by dagrende** [comment]
With the change, It didn't build, unfortunately. The output:

pi@rpi4:~/pytradfri $ ./script/dev_docker 
Sending build context to Docker daemon  1.169MB
Step 1/8 : FROM python:3.9
3.9: Pulling from library/python
fd92fbcda272: Pull complete 
29a6987ee02f: Pull complete 
3d6d85cbb278: Pull complete 
46bd566d277d: Pull complete 
edcf448232b2: Pull complete 
0da5ed0c499f: Pull complete 
521c566328f9: Pull complete 
a8c8425a7db5: Pull complete 
40b0abd675f9: Pull complete 
Digest: sha256:0cfb17836561024a34dde1f34022334ca433877d43c62298cba6115cb082f816
Status: Downloaded newer image for python:3.9
 ---> e6c622162a26
Step 2/8 : RUN apt-get update -y &&   apt-get install -y python3 python3-pip git autoconf automake libtool &&   apt-get clean &&   rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* build/
 ---> Running in 48a9d8f8afaa
Get:1 http://security.debian.org/debian-security bullseye-security InRelease [44.1 kB]
Get:2 http://deb.debian.org/debian bullseye InRelease [116 kB]
Get:3 http://deb.debian.org/debian bullseye-updates InRelease [39.4 kB]
Err:1 http://security.debian.org/debian-security bullseye-security InRelease
  At least one invalid signature was encountered.
Err:2 http://deb.debian.org/debian bullseye InRelease
  At least one invalid signature was encountered.
Err:3 http://deb.debian.org/debian bullseye-updates InRelease
  At least one invalid signature was encountered.
Reading package lists...
W: GPG error: http://security.debian.org/debian-security bullseye-security InRelease: At least one invalid signature was encountered.
E: The repository 'http://security.debian.org/debian-security bullseye-security InRelease' is not signed.
W: GPG error: http://deb.debian.org/debian bullseye InRelease: At least one invalid signature was encountered.
E: The repository 'http://deb.debian.org/debian bullseye InRelease' is not signed.
W: GPG error: http://deb.debian.org/debian bullseye-updates InRelease: At least one invalid signature was encountered.
E: The repository 'http://deb.debian.org/debian bullseye-updates InRelease' is not signed.
The command '/bin/sh -c apt-get update -y &&   apt-get install -y python3 python3-pip git autoconf automake libtool &&   apt-get clean &&   rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* build/' returned a non-zero code: 100

**Comment by ggravlingen** [comment]
This is quite odd. There are a few workarounds here. One thing I would try is a copy/paste of this file’s content into that Dockerfile you just changed:

https://github.com/home-assistant-libs/pytradfri/blob/master/.devcontainer/Dockerfile.dev

**Comment by dagrende** [comment]
If you mean I should replace content of DockerfileRPI with the contents of 'dockerfile.dev above, and rerun ./script/dev_docker, it fails with the output:
```
pi@rpi4:~/pytradfri $ ./script/dev_docker 
Sending build context to Docker daemon  1.169MB
Step 1/10 : ARG VARIANT=3.10-bullseye
Step 2/10 : FROM mcr.microsoft.com/vscode/devcontainers/python:0-${VARIANT}
0-3.10-bullseye: Pulling from vscode/devcontainers/python
no matching manifest for linux/arm/v7 in the manifest list entries
```

**Comment by ggravlingen** [comment]
Unfortunately, I can’t test in my RPI4 as it runs an OS I don’t have direct access to.

if I were to try to solve this for myself, I would look here and see if I could find an image for armv7:
https://hub.docker.com/_/python?tab=tags

Dockerfile.dev works on my Mac and in my PC so that one should be fine to modify and replace the docker image in (update first line of file).

**Comment by ggravlingen** [comment]
Or maybe here is better?
https://hub.docker.com/r/arm32v7/python/

**Comment by dagrende** [comment]
OK. I'll try

/Dag
