### ISSUE TITLE
pytradfri 8.0.1 throws exception

### ISSUE THREAD

**Issue by garynl** [home-assistant-libs/pytradfri#424]
### Where are you using pytradfri (eg stand-alone, Home Assistant etc)
standalone
### Version of pytradfri
8.0.1
### Backend used (aiocoap, libcoap)
libcoap
### What type of environment are you in, eg Dockerized, Raspberry PI, VirtualBox, WiFi network (give as much details as possible)
raspberry pi 3B
### Expected behaviour
standalone interface
### Actual behaviour
$ python3 -i -m pytradfri 192.168.1.xxx
DEBUG:pytradfri.api.libcoap_api:Executing 192.168.1.xxx get ['15001']
DEBUG:pytradfri.api.libcoap_api:Received: 
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pi/.local/lib/python3.7/site-packages/pytradfri/__main__.py", line 138, in <module>
    main(args)
  File "/home/pi/.local/lib/python3.7/site-packages/pytradfri/__main__.py", line 60, in main
    devices_commands = api(gateway.get_devices())
  File "/home/pi/.local/lib/python3.7/site-packages/pytradfri/api/libcoap_api.py", line 100, in request
    return self._execute(api_commands, timeout=timeout)
  File "/home/pi/.local/lib/python3.7/site-packages/pytradfri/api/libcoap_api.py", line 94, in _execute
    api_command.result = _process_output(return_value, parse_json)
  File "/home/pi/.local/lib/python3.7/site-packages/pytradfri/command.py", line 92, in result
    self._result = self._process_result(value)
  File "/home/pi/.local/lib/python3.7/site-packages/pytradfri/gateway.py", line 78, in process_result
    return [self.get_device(dev) for dev in result]
TypeError: 'NoneType' object is not iterable

**Comment by garynl** [comment]
Remove identity json file and the psk from previous runs and the problem is resolved. Sorry
