### ISSUE TITLE
Error parsing  SmartTaskResponse

### ISSUE THREAD

**Issue by MichaelGrafnetter** [home-assistant-libs/pytradfri#491]
### Where are you using pytradfri (eg stand-alone, Home Assistant etc)
Standalone

### Version of pytradfri
11.0.0 (pytradfri-11.0.0-py3-none-any.whl)

### Backend used (aiocoap, libcoap)
libcoap

### What type of environment are you in, eg Dockerized, Raspberry PI, VirtualBox, WiFi network (give as much details as possible)
Debian Linux in VirtualBox

### Actual behaviour
Running pytradfri from command line ends with an exception:
```
...
DEBUG:pytradfri.api.libcoap_api:Executing 192.168.9.63 get ['15010']
DEBUG:pytradfri.api.libcoap_api:Received: [299521,322032,289583]
DEBUG:pytradfri.api.libcoap_api:Executing 192.168.9.63 get ['15010', 299521]
DEBUG:pytradfri.api.libcoap_api:Received: {"9001":"Blinds Up Weekend","9002":1648188767,"9003":299521,"5850":1,"9040":4,"9042":{"5850":1},"9041":96,"9043":{"5850":1,"15016":[{"9003":65569,"5536":0.0},{"9003":65566,"5536":0.0},{"9003":65564,"5536":0.0},{"9003":65570,"5536":0.0}]},"9044":[{"9046":6,"9047":30,"9048":7,"9049":0,"9226":0}]}
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/michael/.local/lib/python3.10/site-packages/pytradfri/__main__.py", line 97, in <module>
    tasks = api(tasks_commands)
  File "/home/michael/.local/lib/python3.10/site-packages/pytradfri/api/libcoap_api.py", line 131, in request
    result = self._execute(api_command, timeout=timeout)
  File "/home/michael/.local/lib/python3.10/site-packages/pytradfri/api/libcoap_api.py", line 106, in _execute
    api_command.process_result(_process_output(return_value, parse_json))
  File "/home/michael/.local/lib/python3.10/site-packages/pytradfri/command.py", line 62, in process_result
    self._result = self._process_result(result)
  File "/home/michael/.local/lib/python3.10/site-packages/pytradfri/gateway.py", line 251, in process_result
    return SmartTask(self, result)
  File "/home/michael/.local/lib/python3.10/site-packages/pytradfri/smart_task.py", line 104, in __init__
    super().__init__(raw)
  File "/home/michael/.local/lib/python3.10/site-packages/pytradfri/resource.py", line 39, in __init__
    self.raw = self._model_class(**raw)
  File "/usr/lib/python3/dist-packages/pydantic/main.py", line 331, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for SmartTaskResponse
9042 -> 15013
  field required (type=value_error.missing)
```

**Comment by MartinHjelmare** [comment]
From your log it looks like we should make the 15013 attribute optional, as it's not present in your response:
https://github.com/home-assistant-libs/pytradfri/blob/029592c889df276325244a7b410e6656b60e7424/pytradfri/smart_task.py#L82

**Comment by ggravlingen** [comment]
> From your log it looks like we should make the 15013 attribute optional, as it's not present in your response:
> 
> https://github.com/home-assistant-libs/pytradfri/blob/029592c889df276325244a7b410e6656b60e7424/pytradfri/smart_task.py#L82

I had a quick look and there are dependencies that need refactoring if we make it optional, which I agree seems to be the right thing to do.

**Comment by MartinHjelmare** [comment]
Maybe default the attribute to an empty list?
