### ISSUE TITLE
Integration fail to load: Retrying setup: ('Request timed out.', TimeoutError())

### ISSUE THREAD

**Issue by starryalley** [home-assistant-libs/pytradfri#662]
### Where are you using pytradfri (eg stand-alone, Home Assistant etc)
Home Assistant 2023.3.5
Tradfri gateway firmware 1.19.52

### Version of pytradfri
The included version in Home Assistant 2023.3.5

### Backend used (aiocoap, libcoap)
aiocoap

### What type of environment are you in, eg Dockerized, Raspberry PI, VirtualBox, WiFi network (give as much details as possible)

Raspberry Pi, home assistant OS. 
Supervisor 2023.03.1
Operating System 9.5

### Expected behaviour

It works for the past 1 year and then suddenly 3am today it stopped working.

### Actual behaviour

It started with _async_update_data() that returned OSError 101 Network Unreachable.

```
2023-03-18 03:24:55.468 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 101] Network unreachable, transport: <_SelectorDatagramTransport fd=28 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 55045)>
2023-03-18 03:24:55.481 ERROR (MainThread) [async_upnp_client.ssdp] Received error: [Errno 99] Address not available, transport: <_SelectorDatagramTransport fd=31 read=polling write=<idle, bufsize=0>>, socket: <asyncio.TransportSocket fd=31, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('::', 45276, 0, 0)>
2023-03-18 03:24:55.494 ERROR (MainThread) [homeassistant.components.tradfri] Unexpected error fetching Update coordinator for <65544 - Study Desk Lamp (TRADFRI bulb E27 WW 806lm)> data: [Errno 101] Network unreachable
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 1052, in sendto
    self._sock.send(data)
OSError: [Errno 101] Network unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 239, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/components/tradfri/coordinator.py", line 77, in _async_update_data
    raise exc
  File "/usr/local/lib/python3.10/site-packages/aiocoap/protocol.py", line 780, in _run_observation
    async for block1_notification in lower_observation:
  File "/usr/local/lib/python3.10/site-packages/aiocoap/protocol.py", line 878, in __anext__
    result = await self._future
  File "/usr/local/lib/python3.10/site-packages/aiocoap/protocol.py", line 897, in __del__
    self._future.result()
aiocoap.error.NetworkError: [Errno 101] Network unreachable
2023-03-18 03:24:55.516 ERROR (MainThread) [homeassistant.components.tradfri] Unexpected error fetching Update coordinator for <65554 - Living Room Desk Lamp (TRADFRI bulb E27 WS opal 1000lm)> data: [Errno 101] Network unreachable
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 1052, in sendto
    self._sock.send(data)
OSError: [Errno 101] Network unreachable
```

And then it stopped working even though the network is completely fine. I tried to update HA to the latest release and try to reload the integration to no avail. This is the log from integration reloading:

Request time out:

```
2023-03-18 21:36:00.851 WARNING (MainThread) [homeassistant.config_entries] Config entry '192.168.1.103' for tradfri integration not ready yet: ('Request timed out.', TimeoutError()); Retrying in background
2023-03-18 22:30:48.620 DEBUG (MainThread) [pytradfri.api.aiocoap_api] Resetting protocol
2023-03-18 22:30:48.629 DEBUG (MainThread) [pytradfri.api.aiocoap_api] Resetting protocol
2023-03-18 22:32:08.719 DEBUG (MainThread) [pytradfri.api.aiocoap_api] REQUEST call: 192.168.1.116 single: <<<{'_method': 'get', '_path': ['15011', '15012'], '_data': None, '_parse_json': True, '_process_result': <function Gateway.get_gateway_info.<locals>.process_result at 0xa08b7f58>, '_err_callback': None, '_observe': False, '_observe_duration': 0, '_raw_result': None, '_result': None}>>>
2023-03-18 22:32:08.720 DEBUG (MainThread) [pytradfri.api.aiocoap_api] Executing 192.168.1.116 <Command get ['15011', '15012']>
2023-03-18 22:32:38.722 DEBUG (MainThread) [pytradfri.api.aiocoap_api] Resetting protocol
2023-03-18 22:32:38.730 DEBUG (MainThread) [pytradfri.api.aiocoap_api] Resetting protocol
2023-03-18 22:33:58.970 DEBUG (MainThread) [pytradfri.api.aiocoap_api] REQUEST call: 192.168.1.116 single: <<<{'_method': 'get', '_path': ['15011', '15012'], '_data': None, '_parse_json': True, '_process_result': <function Gateway.get_gateway_info.<locals>.process_result at 0x9b7e6340>, '_err_callback': None, '_observe': False, '_observe_duration': 0, '_raw_result': None, '_result': None}>>>
2023-03-18 22:33:58.971 DEBUG (MainThread) [pytradfri.api.aiocoap_api] Executing 192.168.1.116 <Command get ['15011', '15012']>
```

**Comment by ggravlingen** [comment]
@starryalley any changes in your network, like a renewed IP address for the gateway? Did you upgrade the firmware of the gateway?

@MartinHjelmare can you please move this issue to `core`, if possible?

**Comment by starryalley** [comment]
IP address is the same. I don't know if gateway firmware was recently updated. Is it normally get updated when the Ikea HomeSmart app opens?

I should have mentioned that I wasn't home for 3 months until recently. It worked all the time until one day after I'm back home. Ikea Home Smart app can't be used across different network so I assume me or my partner may have opened Ikea App that caused a firmware update. But I can't be sure.

**Comment by starryalley** [comment]
If needed I can open an issue somewhere else. 

I saw "Verified Device Compatibility" with a firmware older than I have, hence why I opened this issue here.  My first guess was something changed in the gateway firmware that I have, but I don't know how to view the firmware update history there. But `1.19.52` was released 2 March this year so if it has caused issue someone else should have opened another issue anyway...

**Comment by MartinHjelmare** [comment]
We can't move issues across organizations.

**Comment by starryalley** [comment]
I just tried standalone use of pytradfri on my mac under the same LAN and it works with my gateway. So looks like it is the version in home assistant that doesn't work. It keeps on failing:

```
2023-03-20 02:08:20.739 DEBUG (MainThread) [pytradfri.api.aiocoap_api] REQUEST call: 192.168.1.116 single: <<<{'_method': 'get', '_path': ['15011', '15012'], '_data': None, '_parse_json': True, '_process_result': <function Gateway.get_gateway_info.<locals>.process_result at 0x97c321d8>, '_err_callback': None, '_observe': False, '_observe_duration': 0, '_raw_result': None, '_result': None}>>>
2023-03-20 02:08:20.740 DEBUG (MainThread) [pytradfri.api.aiocoap_api] Executing 192.168.1.116 <Command get ['15011', '15012']>
2023-03-20 02:08:50.743 DEBUG (MainThread) [pytradfri.api.aiocoap_api] Resetting protocol
2023-03-20 02:08:50.752 DEBUG (MainThread) [pytradfri.api.aiocoap_api] Resetting protocol
```

**Comment by starryalley** [comment]
I just looked through the home assistant code and it's using 9.0.1 pytradfri. I've tried to run 9.0.1 standalone and expectedly it also works just fine. It then comes down to that particular hardware (RPi4) that I'm running HA on. 

Restarting HA didn't help. I then tried to delete Tradfri integration and re-added one, didn't help. Then I tried to physcially restart the RPi4. And then magically it works again.

Looks like a hardware/OS/driver or underlying library issue that gets resolved after OS restarts. I'm closing this issue. However I suggest we can modify the supported firmware to `1.19.52`, which is the version I have on my gateway.

**Comment by Mariusthvdb** [comment]
Hey StarryAlley,

don't want to mix issues, but since I am experiencing unexplained Tradfri disconnects since HA januari, could I please ask you to have a look at https://github.com/home-assistant/core/issues/85254?

Ive only been able to automate the reloading of the integration as a temporary solution, so hope you could find similarities and help me out.

thx
