### ISSUE TITLE
All Tradfri Battery sensors are not available anymore

### ISSUE THREAD

**Issue by felixmueller** [home-assistant-libs/pytradfri#868]
### Where are you using pytradfri (eg stand-alone, Home Assistant etc)
Home Assistant

### Version of pytradfri
Version included in HA Core 2024.5.3
Version of Tradfri Gateway: 1.21.31

### What type of environment are you in, eg Dockerized, Raspberry PI, VirtualBox, WiFi network (give as much details as possible)
HA OS Supervised

### Expected behaviour
All Tradfri Battery sensors are available as before.

### Actual behaviour
All Tradfri Battery sensors are not available anymore.

Error in the log pointing to this lib (firmware version):

> Error while setting up tradfri platform for sensor
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 356, in _async_setup_platform
> await asyncio.shield(awaitable)
> File "/usr/src/homeassistant/homeassistant/components/tradfri/sensor.py", line 162, in async_setup_entry
> TradfriSensor(
> File "/usr/src/homeassistant/homeassistant/components/tradfri/sensor.py", line 186, in init
> super().init(
> File "/usr/src/homeassistant/homeassistant/components/tradfri/base_class.py", line 65, in init
> sw_version=info.firmware_version,
> ^^^^^^^^^^^^^^^^^^^^^
> File "/usr/local/lib/python3.12/site-packages/pytradfri/device/init.py", line 177, in firmware_version
> return self.raw[ATTR_DEVICE_FIRMWARE_VERSION]
> ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> KeyError: '3'

**Comment by felixmueller** [comment]
Update: today all battery sensors suddenly came back to life without altering anything ¯\\\_(ツ)\_/¯
<img width="528" alt="tradfri-batteries" src="https://github.com/home-assistant-libs/pytradfri/assets/115331/b234be7d-46e7-4cf7-a818-35442f1e8982">
